apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "udrive.fullname" . }}-csp
  labels:
    {{- include "udrive.labels" . | nindent 4 }}
data:
  csp.yaml: |
    directives:
      default-src:
        - "'none'"
      script-src:
        - "'self'"
        - "'unsafe-inline'"
        - "https://static.cloudflareinsights.com"
      style-src:
        - "'self'"
        - "'unsafe-inline'"
      img-src:
        - "'self'"
        - "data:"
        - "blob:"
        - "https://raw.githubusercontent.com/owncloud/awesome-ocis/"
        - "https://localhost:9980"
        - "https://127.0.0.1:9980"
        - "http://localhost:9980"
        - "http://127.0.0.1:9980"
        - "https://office.unity-workspace.com"
      font-src:
        - "'self'"
        - "data:"
      connect-src:
        - "'self'"
        - "blob:"
        - "https://raw.githubusercontent.com/owncloud/awesome-ocis/"
        - "https://localhost:9980"
        - "https://127.0.0.1:9980"
        - "http://localhost:9980"
        - "http://127.0.0.1:9980"
        - "wss://localhost:9980"
        - "wss://127.0.0.1:9980"
        - "ws://localhost:9980"
        - "ws://127.0.0.1:9980"
        - "https://office.unity-workspace.com"
        - "wss://office.unity-workspace.com"
        - "https://auth.unity-workspace.com"
        - "https://cloudflareinsights.com"
      media-src:
        - "'self'"
        - "blob:"
      object-src:
        - "'self'"
        - "blob:"
      child-src:
        - "'self'"
      frame-src:
        - "'self'"
        - "blob:"
        - "https://embed.diagrams.net/"
        - "https://localhost:9980"
        - "https://127.0.0.1:9980"
        - "http://localhost:9980"
        - "http://127.0.0.1:9980"
        - "https://office.unity-workspace.com"
        - "https://auth.unity-workspace.com"
      frame-ancestors:
        - "'self'"
      manifest-src:
        - "'self'"
