{{- if not .Values.vault.enabled }}
{{- if not .Values.udrive.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udrive.fullname" . }}
  labels:
    {{- include "udrive.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.udrive.admin.password }}
  admin-password: {{ .Values.udrive.admin.password | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if and (eq .Values.storage.driver "s3ng") (not .Values.storage.s3.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udrive.fullname" . }}-s3
  labels:
    {{- include "udrive.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.storage.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.storage.s3.secretKey | b64enc | quote }}
{{- end }}
{{- if and (eq .Values.storage.driver "s3ng") .Values.storage.s3.caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "udrive.fullname" . }}-ca
  labels:
    {{- include "udrive.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.storage.s3.caCert | b64enc | quote }}
{{- end }}
{{- end }}
