{{- if and .Values.vault.enabled .Values.vault.caCert -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default (printf "%s-vault-ca" (include "udrive.fullname" .)) .Values.vault.caConfigMap }}
  labels:
    {{- include "udrive.labels" . | nindent 4 }}
data:
  vault-ca.crt: {{ .Values.vault.caCert | quote }}
{{- end }}
